SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${SCRIPT_DIR}"/getenv.sh
basePath="$1"
if [ -z "$basePath" ]; then
    basePath=$(realpath "${SCRIPT_DIR}/../..")
fi
outputPath="$basePath/$HTTP_CERT_PATH"
mkdir -p "$outputPath" 2>/dev/null || {
    echo "${RED}Error: Invalid basePath: $basePath.${RESET}"
    exit 1
}
windowsPath=$(wslpath -w "$outputPath")
winDotNet=$(cmd.exe /c where dotnet.exe 2>/dev/null | tr -d '\r')
password=$(uuidgen | tr -d '-')
cmd.exe /c "${winDotNet}" dev-certs https -ep "$windowsPath\\$HTTP_CERT_FILENAME".crt --format pem --trust -np 2>/dev/null
cmd.exe /c "${winDotNet}" dev-certs https -ep "$windowsPath\\$HTTP_CERT_FILENAME".pfx -p "$password" 2>/dev/null
now=$(date -u)
fileContents="# This file was generated by exportcert.sh - 1.0.0
Kestrel__Certificates__Default__Password=$password"
echo "$fileContents" > "$outputPath/https.env"
echo "Generated Windows host dotnet developer certificates."
echo -e "Export folder: $outputPath."
